version: '3.8'

services:
  api:
    build: .
    volumes:
      - .:/app
      - ./jts.ini:/home/ibgateway/Jts/jts.ini
      - ./tws.xml:/home/ibgateway/Jts/tws.xml
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      db_host: ${db_host}
      mail_sender: ${mail_sender}
      mail_receiver: ${mail_receiver}
      mail_password: ${mail_password}
      ib_gateway_host: ib-gateway
      ib_gateway_port: ${ib_gateway_port}
      ib_client_id: ${ib_client_id}
    networks:
      - trade_network
    depends_on:
      ib-gateway:
        condition: service_started
      db:
        condition: service_started

  ib-gateway:
    image: ghcr.io/unusualalpha/ib-gateway:10.20.1h
    environment:
      - CUSTOM_CONFIG=yes
      - IB_GATEWAY_USER=${IB_GATEWAY_USER}
      - IB_GATEWAY_PW=${IB_GATEWAY_PW}
      - TRADING_MODE=${TRADING_MODE}
    networks:
      - trade_network
    volumes:
      - ./jts.ini:/home/ibgateway/Jts/jts.ini
      - ./tws.xml:/home/ibgateway/Jts/tws.xml
    expose:
      - "4001"
      - "4002"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c 'echo > /dev/tcp/localhost/4002' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - trade_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - trade_network
    depends_on:
      - db
    expose:
      - "80"

volumes:
  postgres_data:

networks:
  trade_network:
    driver: bridge